stryker4s {
  # This file is read when running `Core/stryker` because sbt-stryker4s sets the
  # base dir to the subproject folder (`core/`).

  mutate = [
    "src/main/scala/**/*.scala",
    "!**/target/**",
    "!.metals/**",
    "!.bloop/**",
    "!.idea/**"
  ]

  scala-dialect = "scala3"

  reporters = [ "console", "html", "json" ]

  thresholds {
    high = 80
    low = 60
    break = 0
  }

  static-tmp-dir = true
  clean-tmp-dir = true
  concurrency = 2
  timeout-factor = 2.0
  timeout = "5s"
}

